# Generated by Django 5.1.6 on 2025-02-22 13:24

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[users.validators.validate_nip], verbose_name='NIP'),
        ),
    ]
