# Generated by Django 5.1.6 on 2025-02-22 13:24

import django.db.models.deletion
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa normy badawczej np. PN-EN 206', max_length=50, unique=True, verbose_name='Norma badawcza')),
                ('method', models.CharField(help_text='Metoda badania np. Wytrzymałość na ściskanie', max_length=50)),
            ],
            options={
                'verbose_name': 'Norma Badawcza',
                'verbose_name_plural': 'Normy Badawcze',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa próbki')),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('UNS', 'Unselected'), ('CON', 'Concrete'), ('EXF', 'Exterior Facade'), ('SPS', 'Sports Surface'), ('OFF', 'Pull-off'), ('WAP', 'Wallpaper'), ('SYT', 'Synthetic Turf'), ('PLA', 'Plaster and Adhesives'), ('CPR', 'Concrete Prefabricated Products'), ('FLC', 'Floor Covering'), ('SAN', 'Sanitary Product'), ('EXS', 'Exterior Shutters')], default='UNS', max_length=3, validators=[projects.validators.validate_material_type])),
                ('collection_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Próbka',
                'verbose_name_plural': 'Próbki',
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa projektu')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awaiting approval', 'Awaiting Approval')], default='open', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(limit_choices_to={'groups__name': 'Lab_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_assignee', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='Numer sprawozdania (litery/numery/-)', max_length=16, unique=True, validators=[projects.validators.validate_code_name], verbose_name='Numer sprawozdania')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Lab_member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Akceptacja wyników:')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Sprawozdanie',
                'verbose_name_plural': 'Sprawozdania',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportResearchStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=16, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.report')),
                ('research_standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.researchstandard')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='research_standards',
            field=models.ManyToManyField(related_name='reports', through='projects.ReportResearchStandard', to='projects.researchstandard'),
        ),
        migrations.AddField(
            model_name='report',
            name='sample',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='projects.sample'),
        ),
        migrations.AddConstraint(
            model_name='reportresearchstandard',
            constraint=models.UniqueConstraint(fields=('report', 'research_standard'), name='unique_report_standard'),
        ),
    ]
