# Generated by Django 5.1.6 on 2025-02-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchstandard',
            name='name',
            field=models.CharField(help_text='Nazwa normy badawczej np. PN-EN 206', max_length=50, verbose_name='Norma badawcza'),
        ),
    ]
