# Generated by Django 5.1.6 on 2025-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_researchstandard_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='researchstandard',
            constraint=models.UniqueConstraint(fields=('name', 'method'), name='unique_standard_method'),
        ),
    ]
