# Generated by Django 5.1.6 on 2025-02-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_researchstandard_unique_standard_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekty'},
        ),
    ]
